# Generated by Django 5.2.3 on 2025-06-28 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Problem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("code", models.CharField(default="TEMP", max_length=50, unique=True)),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("Easy", "Easy"),
                            ("Medium", "Medium"),
                            ("Hard", "Hard"),
                        ],
                        max_length=10,
                    ),
                ),
                ("time_limit", models.IntegerField(default=1)),
                ("memory_limit", models.IntegerField(default=128)),
                ("description", models.TextField()),
                ("input_format", models.TextField(blank=True)),
                ("output_format", models.TextField(blank=True)),
                ("constraints", models.TextField(blank=True)),
                ("sample_input", models.TextField(blank=True)),
                ("sample_output", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="TestCase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("input", models.TextField()),
                ("output", models.TextField()),
                (
                    "problem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="testcases",
                        to="problems.problem",
                    ),
                ),
            ],
        ),
    ]
