# Generated by Django 5.2.3 on 2025-06-29 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='use_docker',
            field=models.BooleanField(default=True),
        ),
    ]
