# Generated by Django 5.2.3 on 2025-06-24 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='code',
            field=models.CharField(default='TEMP', max_length=50, unique=True),
        ),
    ]
