# Generated by Django 5.2.3 on 2025-06-24 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0002_problem_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='full_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
