# Generated by Django 5.2.3 on 2025-06-26 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("judge", "0004_alter_testcase_problem"),
    ]

    operations = [
        migrations.RenameField(
            model_name="problem",
            old_name="statement",
            new_name="description",
        ),
        migrations.AddField(
            model_name="problem",
            name="constraints",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="problem",
            name="input_format",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="problem",
            name="output_format",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="problem",
            name="sample_input",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="problem",
            name="sample_output",
            field=models.TextField(blank=True),
        ),
    ]
