# Generated by Django 5.2.3 on 2025-06-26 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("judge", "0005_rename_statement_problem_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="problem",
            name="difficulty",
            field=models.CharField(
                choices=[("Easy", "Easy"), ("Medium", "Medium"), ("Hard", "Hard")],
                max_length=10,
            ),
        ),
    ]
