# Generated by Django 5.2.3 on 2025-06-28 03:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0006_alter_problem_difficulty'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='submitted_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
