# Generated by Django 5.2.3 on 2025-06-28 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("judge", "0008_contest_contestsubmission"),
        ("problems", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contestsubmission",
            name="problem",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contest_submissions",
                to="problems.problem",
            ),
        ),
        migrations.AlterField(
            model_name="submission",
            name="problem",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="problems.problem"
            ),
        ),
        migrations.AlterField(
            model_name="contest",
            name="problems",
            field=models.ManyToManyField(
                related_name="contests", to="problems.problem"
            ),
        ),
        migrations.DeleteModel(
            name="TestCase",
        ),
        migrations.DeleteModel(
            name="Problem",
        ),
    ]
