# Generated by Django 5.2.3 on 2025-06-29 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0009_alter_contestsubmission_problem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='code_file_path',
            field=models.TextField(blank=True, null=True),
        ),
    ]
