# Generated by Django 5.2.3 on 2025-06-29 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0010_submission_code_file_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestsubmission',
            name='code_file_path',
            field=models.TextField(blank=True, null=True),
        ),
    ]
