# Generated by Django 5.2.3 on 2025-07-04 18:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("judge", "0011_contestsubmission_code_file_path"),
    ]

    operations = [
        migrations.AddField(
            model_name="contest",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
